version: '3'

services:
  app:
    image: my-laravel-app
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_URL=http://my-laravel-app:9000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crowdfunding_app
      - DB_USERNAME=root
      - DB_PASSWORD=Epohara_99
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Epohara_99
      MYSQL_DATABASE: crowdfunding_app

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    depends_on:
      - app

networks:
  my-net:
    driver: bridge

